import images from "./Images"; // Import shoes data

const shoesData = [
    { id: 1, name: "Nike Air Max", category: "Sports", gender: "Men", company: "Nike", price: 150, discount: 10, image: images.shoes1 },
    { id: 2, name: "Adidas Ultraboost", category: "Runner", gender: "Women", company: "Adidas", price: 180, discount: 15, image: images.shoes2 },
    { id: 3, name: "Puma Ignite", category: "Casual", gender: "Men", company: "Puma", price: 120, discount: 8, image: images.shoes3 },
    { id: 4, name: "Bata Formal Shoes", category: "Formal", gender: "Women", company: "Bata", price: 90, discount: 5, image: images.shoes4 },
    { id: 5, name: "Apex Comfort Walk", category: "Casual", gender: "Men", company: "Apex", price: 100, discount: 7, image: images.shoes5 },
    { id: 6, name: "Nike Revolution", category: "Runner", gender: "Women", company: "Nike", price: 140, discount: 12, image: images.shoes6 },
    { id: 7, name: "Adidas Gazelle", category: "Casual", gender: "Men", company: "Adidas", price: 130, discount: 10, image: images.shoes7 },
    { id: 8, name: "Puma Suede Classic", category: "Casual", gender: "Women", company: "Puma", price: 110, discount: 6, image: images.shoes8 },
    { id: 9, name: "Bata Executive", category: "Formal", gender: "Men", company: "Bata", price: 85, discount: 4, image: images.shoes9 },
    { id: 10, name: "Apex Athletic", category: "Runner", gender: "Women", company: "Apex", price: 125, discount: 9, image: images.shoes10 },
    { id: 11, name: "Nike Zoom Fly", category: "Runner", gender: "Men", company: "Nike", price: 160, discount: 12, image: images.shoes11 },
    { id: 12, name: "Adidas Superstar", category: "Casual", gender: "Women", company: "Adidas", price: 135, discount: 11, image: images.shoes12 },
    { id: 13, name: "Puma Future", category: "Sports", gender: "Men", company: "Puma", price: 145, discount: 13, image: images.shoes13 },
    { id: 14, name: "Bata Leather Loafers", category: "Formal", gender: "Women", company: "Bata", price: 95, discount: 6, image: images.shoes14 },
    { id: 15, name: "Apex Daily Walk", category: "Casual", gender: "Men", company: "Apex", price: 105, discount: 8, image: images.shoes15 },
    { id: 16, name: "Nike Metcon", category: "Sports", gender: "Women", company: "Nike", price: 170, discount: 14, image: images.shoes16 },
    { id: 17, name: "Adidas NMD R1", category: "Casual", gender: "Men", company: "Adidas", price: 140, discount: 10, image: images.shoes17 },
    { id: 18, name: "Puma X-Ray", category: "Casual", gender: "Women", company: "Puma", price: 120, discount: 8, image: images.shoes18 },
    { id: 19, name: "Bata Derby", category: "Formal", gender: "Men", company: "Bata", price: 90, discount: 5, image: images.shoes19 },
    { id: 20, name: "Apex Energy", category: "Runner", gender: "Women", company: "Apex", price: 130, discount: 9, image: images.shoes20 },
    { id: 21, name: "Nike Free Run", category: "Runner", gender: "Men", company: "Nike", price: 150, discount: 12, image: images.shoes21 },
    { id: 22, name: "Adidas Continental", category: "Casual", gender: "Women", company: "Adidas", price: 125, discount: 9, image: images.shoes22 },
    { id: 23, name: "Puma Cell Surin", category: "Sports", gender: "Men", company: "Puma", price: 140, discount: 11, image: images.shoes23 },
    { id: 24, name: "Bata Oxford Shoes", category: "Formal", gender: "Women", company: "Bata", price: 100, discount: 7, image: images.shoes24 },
    { id: 25, name: "Apex Classic", category: "Casual", gender: "Men", company: "Apex", price: 115, discount: 8, image: images.shoes25 },


    { id: 26, name: "Puma Flyer Runner", category: "Runner", gender: "Women", company: "Puma", price: 110, discount: 10, image: images.shoes26 },
    { id: 27, name: "Nike Quest 4", category: "Sports", gender: "Men", company: "Nike", price: 125, discount: 12, image: images.shoes27 },
    { id: 28, name: "Adidas NMD R1", category: "Casual", gender: "Women", company: "Adidas", price: 115, discount: 9, image: images.shoes28 },
    { id: 29, name: "Bata Leather Shoes", category: "Formal", gender: "Men", company: "Bata", price: 90, discount: 8, image: images.shoes29 },
    { id: 30, name: "Apex Trend", category: "Casual", gender: "Women", company: "Apex", price: 100, discount: 6, image: images.shoes30 },
    { id: 31, name: "Nike Free RN", category: "Runner", gender: "Men", company: "Nike", price: 135, discount: 10, image: images.shoes31 },
    { id: 32, name: "Adidas Ultraboost 21", category: "Sports", gender: "Women", company: "Adidas", price: 140, discount: 15, image: images.shoes32 },
    { id: 33, name: "Puma Carson", category: "Casual", gender: "Men", company: "Puma", price: 105, discount: 7, image: images.shoes33 },
    { id: 34, name: "Bata Elegant", category: "Formal", gender: "Women", company: "Bata", price: 85, discount: 6, image: images.shoes34 },
    { id: 35, name: "Apex Sporty", category: "Sports", gender: "Men", company: "Apex", price: 115, discount: 9, image: images.shoes35 },
    { id: 36, name: "Nike Vaporfly", category: "Runner", gender: "Women", company: "Nike", price: 155, discount: 14, image: images.shoes36 },
    { id: 37, name: "Adidas Terrex", category: "Sports", gender: "Men", company: "Adidas", price: 130, discount: 12, image: images.shoes37 },
    { id: 38, name: "Puma SoftRide", category: "Casual", gender: "Women", company: "Puma", price: 95, discount: 6, image: images.shoes38 },
    { id: 39, name: "Bata Executive Plus", category: "Formal", gender: "Men", company: "Bata", price: 90, discount: 8, image: images.shoes39 },
    { id: 40, name: "Apex Ultra", category: "Casual", gender: "Women", company: "Apex", price: 105, discount: 7, image: images.shoes40 },
    { id: 41, name: "Nike Infinity React", category: "Runner", gender: "Men", company: "Nike", price: 145, discount: 12, image: images.shoes41 },
    { id: 42, name: "Adidas X9000", category: "Casual", gender: "Women", company: "Adidas", price: 110, discount: 9, image: images.shoes42 },
    { id: 43, name: "Puma Deviate Nitro", category: "Runner", gender: "Men", company: "Puma", price: 120, discount: 10, image: images.shoes43 },
    { id: 44, name: "Bata Prime", category: "Formal", gender: "Women", company: "Bata", price: 80, discount: 5, image: images.shoes44 },
    { id: 45, name: "Apex Street", category: "Casual", gender: "Men", company: "Apex", price: 100, discount: 6, image: images.shoes45 },
    { id: 46, name: "Nike React Vision", category: "Sports", gender: "Women", company: "Nike", price: 130, discount: 11, image: images.shoes46 },
    { id: 47, name: "Adidas Ozweego", category: "Casual", gender: "Men", company: "Adidas", price: 95, discount: 6, image: images.shoes47 },
    { id: 48, name: "Puma Electrify", category: "Runner", gender: "Women", company: "Puma", price: 115, discount: 9, image: images.shoes48 },
    { id: 49, name: "Bata Supreme", category: "Formal", gender: "Men", company: "Bata", price: 85, discount: 7, image: images.shoes49 },
    { id: 50, name: "Apex Pro Runner", category: "Runner", gender: "Women", company: "Apex", price: 125, discount: 10, image: images.shoes50 },
    { id: 51, name: "Nike Air Zoom Pegasus", category: "Runner", gender: "Men", company: "Nike", price: 140, discount: 10, image: images.shoes51 },
    { id: 52, name: "Adidas Predator", category: "Sports", gender: "Women", company: "Adidas", price: 130, discount: 12, image: images.shoes52 },
    { id: 53, name: "Puma RS-X", category: "Casual", gender: "Men", company: "Puma", price: 110, discount: 8, image: images.shoes53 },
    { id: 54, name: "Bata Classic Leather", category: "Formal", gender: "Women", company: "Bata", price: 90, discount: 6, image: images.shoes54 },
    { id: 55, name: "Apex Motion", category: "Runner", gender: "Men", company: "Apex", price: 120, discount: 9, image: images.shoes55 },
    { id: 56, name: "Nike ZoomX Vaporfly", category: "Sports", gender: "Women", company: "Nike", price: 155, discount: 15, image: images.shoes56 },
    { id: 57, name: "Adidas Solar Glide", category: "Runner", gender: "Men", company: "Adidas", price: 135, discount: 11, image: images.shoes57 },
    { id: 58, name: "Puma Future Rider", category: "Casual", gender: "Women", company: "Puma", price: 100, discount: 7, image: images.shoes58 },
    { id: 59, name: "Bata Executive Black", category: "Formal", gender: "Men", company: "Bata", price: 85, discount: 5, image: images.shoes59 },
    { id: 60, name: "Apex Urban Sport", category: "Casual", gender: "Women", company: "Apex", price: 95, discount: 6, image: images.shoes60 },
    { id: 61, name: "Nike Downshifter", category: "Runner", gender: "Men", company: "Nike", price: 125, discount: 9, image: images.shoes61 },
    { id: 62, name: "Adidas 4D Run", category: "Sports", gender: "Women", company: "Adidas", price: 145, discount: 13, image: images.shoes62 },
    { id: 63, name: "Puma UltraRide", category: "Casual", gender: "Men", company: "Puma", price: 110, discount: 8, image: images.shoes63 },
    { id: 64, name: "Bata Brown Loafers", category: "Formal", gender: "Women", company: "Bata", price: 95, discount: 6, image: images.shoes64 },
    { id: 65, name: "Apex Marathon", category: "Runner", gender: "Men", company: "Apex", price: 130, discount: 10, image: images.shoes65 },
    { id: 66, name: "Nike Free RN 5.0", category: "Runner", gender: "Women", company: "Nike", price: 140, discount: 12, image: images.shoes66 },
    { id: 67, name: "Adidas Retropy", category: "Casual", gender: "Men", company: "Adidas", price: 115, discount: 7, image: images.shoes67 },
    { id: 68, name: "Puma Velocity Nitro", category: "Sports", gender: "Women", company: "Puma", price: 135, discount: 11, image: images.shoes68 },
    { id: 69, name: "Bata Slip-On", category: "Formal", gender: "Men", company: "Bata", price: 90, discount: 5, image: images.shoes69 },
    { id: 70, name: "Apex Endurance", category: "Runner", gender: "Women", company: "Apex", price: 125, discount: 8, image: images.shoes70 },
    { id: 71, name: "Nike Air Monarch", category: "Casual", gender: "Men", company: "Nike", price: 100, discount: 7, image: images.shoes71 },
    { id: 72, name: "Adidas Climacool", category: "Runner", gender: "Women", company: "Adidas", price: 120, discount: 9, image: images.shoes72 },
    { id: 73, name: "Puma Mega NRGY", category: "Sports", gender: "Men", company: "Puma", price: 130, discount: 11, image: images.shoes73 },
    { id: 74, name: "Bata Business Shoes", category: "Formal", gender: "Women", company: "Bata", price: 85, discount: 4, image: images.shoes74 },
    { id: 75, name: "Apex Trail Runner", category: "Runner", gender: "Men", company: "Apex", price: 110, discount: 7, image: images.shoes75 },
    { id: 76, name: "Nike Renew Ride", category: "Casual", gender: "Women", company: "Nike", price: 105, discount: 6, image: images.shoes76 },
    { id: 77, name: "Adidas Adizero Boston", category: "Runner", gender: "Men", company: "Adidas", price: 135, discount: 10, image: images.shoes77 },
    { id: 78, name: "Puma Cali Sport", category: "Casual", gender: "Women", company: "Puma", price: 95, discount: 5, image: images.shoes78 },
    { id: 79, name: "Bata Classic Brown", category: "Formal", gender: "Men", company: "Bata", price: 80, discount: 4, image: images.shoes79 },
    { id: 80, name: "Apex Lightweight", category: "Runner", gender: "Women", company: "Apex", price: 120, discount: 9, image: images.shoes80 },
    { id: 81, name: "Nike React Miler", category: "Runner", gender: "Men", company: "Nike", price: 145, discount: 12, image: images.shoes81 },
    { id: 82, name: "Adidas EQT Gazelle", category: "Casual", gender: "Women", company: "Adidas", price: 110, discount: 8, image: images.shoes82 },
    { id: 83, name: "Puma Ralph Sampson", category: "Sports", gender: "Men", company: "Puma", price: 125, discount: 9, image: images.shoes83 },
    { id: 84, name: "Bata Premium Leather", category: "Formal", gender: "Women", company: "Bata", price: 95, discount: 6, image: images.shoes84 },
    { id: 85, name: "Apex Energy Boost", category: "Runner", gender: "Men", company: "Apex", price: 130, discount: 11, image: images.shoes85 },
    { id: 86, name: "Nike React Infinity", category: "Runner", gender: "Women", company: "Nike", price: 140, discount: 12, image: images.shoes86 },
    { id: 87, name: "Adidas ZX 750", category: "Casual", gender: "Men", company: "Adidas", price: 115, discount: 7, image: images.shoes87 },
    { id: 88, name: "Puma Speed Cat", category: "Sports", gender: "Women", company: "Puma", price: 120, discount: 9, image: images.shoes88 },
    { id: 89, name: "Bata Derby Shoes", category: "Formal", gender: "Men", company: "Bata", price: 85, discount: 5, image: images.shoes89 },
    { id: 90, name: "Apex Max Comfort", category: "Casual", gender: "Women", company: "Apex", price: 100, discount: 6, image: images.shoes90 },
];


export default shoesData;
